string = "i am a good boy"
#print(string[-2])
#print(string[2]);
print(string[1:])
print(string[1:6])
print(string[:9])
print(string[:-2])
print(string[-2:])
print("s" in string)
print(string+string)
print(string*2)
print(string.capitalize())
print(string.count("a",0,12))
print(string.upper())
print(string.swapcase())
print(string.find("a",0,12))
print(string.rfind("a",0,12))
print(string.index("a",0,12))
print(string.islower())
